### ISSUE TITLE
Song lists on the main-page are overlapping while a song is playing and favicon is not updated

### ISSUE THREAD

**Issue by parthiv011** [adityakmrmishra/Geet#11]
![Screenshot (42)](https://github.com/adityakmrmishra/Geet/assets/118474748/ddf7b459-4631-4bb0-9bfc-2ecaab712541)

**Comment by l-ashish-gupta-l** [comment]
Hi there,

Thank you for bringing these issues to our attention. We appreciate your feedback.

Regarding the song list overlap and favicon update issues, we are aware of them and currently working on resolving them in the next GEET version. Your patience is greatly appreciated while we address these matters.

In the meantime, we have some exciting news to share. We are planning significant UI/UX changes for the upcoming version of GEET. If you're interested in contributing to the design, we would love to have your input. Please consider sharing your Figma designs or design concepts with us, and if your UI/UX design is selected by our team, we will be happy to assign you to work on it. Your contributions can make a real impact on the next version of GEET.

Once again, thank you for reaching out and for your support. We look forward to seeing your design ideas and working together to improve GEET.

**Comment by parthiv011** [comment]
I can help with fixing this can you asssign me this?

**Comment by l-ashish-gupta-l** [comment]
If you happen to have a more innovative Figma design in mind, please don't hesitate to share it with us. We're in the process of crafting an enhanced version of GEET with fresh UI/UX elements. Your current changes or contribution is being considered for this new UI/UX of GEET, so it may be irrelevant to open this particular issue and assign you for something that may not apply in the future.

Instead, we invite you to contribute to the upcoming UI/UX improvements. If your design aligns with our vision, we will gladly assign you to work on it, and you can actively participate in coding and contributing to the project.

Thank you for your valuable contributions!
