### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by himanshu07gupta** [adityakmrmishra/Geet#15]
**Is your feature request related to a problem? Please describe.**
My feature request is related to enhancing the user experience. It would be beneficial to have a dedicated login page for older users to access their accounts efficiently.

**Describe the solution you'd like**
I plan to create the necessary pages using HTML and CSS to implement the requested features. These pages will include  a dedicated login page for existing users.
The login page will include fields for basic user details, such as username and password.
I will add login button between search box and (Dark/light) theme button.

**Comment by Anjali2312-Thombare** [comment]
Hey @adityakmrmishra  i will solve this issue as soon as possible  please assign me this issue
