### ISSUE TITLE
  Spelling Mistake in "Create Playlist" Option

### ISSUE THREAD

**Issue by sanjay78632** [adityakmrmishra/Geet#16]
Bug Description
There is a spelling mistake in the "Create Playlist" option. The word "create" is misspelled as "creat."

To Reproduce

Go to the music player application.
Click on the "Create Playlist" option.
Observe the text or form.
Expected Behavior
The "Create Playlist" option should be spelled correctly as "Create Playlist."

Screenshots
If applicable, see the screenshot below highlighting the spelling mistake:
<img width="142" alt="spelling-mistake" src="https://github.com/adityakmrmishra/Geet/assets/111103046/5fb17e4c-aa3c-44cb-bbaf-c9d34957da6e">

Additional Context
This spelling mistake should be corrected to ensure a better user experience and clarity in the application.

**Comment by rutulganatra** [comment]
I want to work on this can you please assign this to me?

**Comment by sanjay78632** [comment]
I want to solve this issue as I have found it 😊
