### ISSUE TITLE
Add attractive colors

### ISSUE THREAD

**Issue by uday-kiran-001** [adityakmrmishra/Geet#19]
NOTE: ----Please add 'hactoberfest' topic to the repository----

**Is your feature request related to a problem? Please describe.**
The colors doesn't look appealing (gray, yellow) which is not attractive.

**Describe the solution you'd like**
I would like to change colors to make the app look appealing and attractive.

<img width="805" alt="Screenshot 2023-10-02 151007" src="https://github.com/adityakmrmishra/Geet/assets/116891059/31af271c-6535-4e38-a9ff-6c4f97ad1b47">

-- I would like to contribute to this as part of hacktoberfest 2023.  While assigning, please add labels - 'hactoberfest', 'hactoberfest-accepted'
@GuryonAnkit

**Comment by GuryonAnkit** [comment]
We're looking for Figma design proposals to enhance our project's UI/UX. If you have design ideas or mockups, please share them in Figma and link them
