### ISSUE TITLE
Bug in Search bar

### ISSUE THREAD

**Issue by uday-kiran-001** [adityakmrmishra/Geet#20]
**Describe the bug**
Placeholder of search bar is 'Search musics'. I think it would be _very clear_ if  it is 'Search songs'

<img width="592" alt="Screenshot 2023-10-02 171612" src="https://github.com/adityakmrmishra/Geet/assets/116891059/cd4b1087-9f97-4bde-95f9-41cdbeef0bd0">

**Additional context**
I would like to contribute to it. Please add 'hactoberfest', 'hactoberfest-accepted' labels while assigning. Thanks.

@GuryonAnkit @adityakmrmishra @adisuyash

**Comment by uday-kiran-001** [comment]
@adityakmrmishra @GuryonAnkit Please assign it so that I can start working on it.

**Comment by uday-kiran-001** [comment]
@adityakmrmishra @l-ashish-gupta-l @GuryonAnkit Please assign this issue to me.

**Comment by l-ashish-gupta-l** [comment]
Hey there,

We're actively working on a new version of GEET, and while we appreciate your contribution, it might not be in line with the future direction we're taking. If you have ideas or skills that align with our vision for the next version, we'd love to hear from you and potentially assign you to more future-oriented tasks.

Thank you for your interest and willingness to contribute to GEET.

**Comment by uday-kiran-001** [comment]
> Hey there,
> 
> We're actively working on a new version of GEET, and while we appreciate your contribution, it might not be in line with the future direction we're taking. If you have ideas or skills that align with our vision for the next version, we'd love to hear from you and potentially assign you to more future-oriented tasks.
> 
> Thank you for your interest and willingness to contribute to GEET.

I think issue #21 is a valid issue. Can you assign it to me? Thanks.
