### ISSUE TITLE
Bug in Search results

### ISSUE THREAD

**Issue by uday-kiran-001** [adityakmrmishra/Geet#21]
**Describe the bug**
Look at the image below. Search results is going below the icons of the songs.

**Screenshots**
<img width="617" alt="Screenshot 2023-10-02 173014" src="https://github.com/adityakmrmishra/Geet/assets/116891059/ed395aec-b3b8-489c-832c-b43caf605dbc">

**Expected behavior**
Search results should be on top of all elements so that it will be visible to the user.

**Additional context**
I would like to contribute to it. Please add 'hactoberfest', 'hactoberfest-accepted' labels while assigning. Thanks.
@adityakmrmishra @GuryonAnkit

**Comment by uday-kiran-001** [comment]
@adityakmrmishra @GuryonAnkit Please assign it so that I can start working on it.

**Comment by uday-kiran-001** [comment]
@adityakmrmishra @l-ashish-gupta-l @GuryonAnkit Please assign this issue to me. I'm ready with my solution for this issue

**Comment by uday-kiran-001** [comment]
@adityakmrmishra @GuryonAnkit  Can you please assign this issue to me. I have a solution ready for this.

**Comment by uday-kiran-001** [comment]
@adityakmrmishra I solved the above mentioned issue, but once have a look at the image below. The results are not clearly visible due to background color of the search results element.

<img width="239" alt="Screenshot 2023-10-04 175710" src="https://github.com/adityakmrmishra/Geet/assets/116891059/524900de-ed06-4aa5-9344-3b11a695f58c">

I would like to slightly update/change background color for the search results so that, it would be clearly visible. I want to suggest about changing it _for time being_ (Until you get a good figma design). Please tell me you opinion on it.

**Comment by adityakmrmishra** [comment]
Okk go ahead

**Comment by adityakmrmishra** [comment]
Okk go ahead

**Comment by uday-kiran-001** [comment]
> Okk go ahead

I've raised the issue #30  can you please assign it to me. It would be very helpful for Hacktoberfest. 
Thanks for your response.
