### ISSUE TITLE
Addition of Top Searched Artists and Top Playlists section

### ISSUE THREAD

**Issue by kartikp962** [adityakmrmishra/Geet#24]
**Is your feature request related to a problem? Please describe.**
My feature request is to make the user have more choices. It would be amazing because having more options would give user to explore and ultimately increases their time on the Geet platform.

**Describe the solution you'd like**
I am thinking to write the necessary code for it in HTML, CSS and JS. My plan is to make it clickable also.  When user will click on the card then the whole playlist of the songs related to that card would start playing.

I will add these sections below the popular artists section.

<img width="877" alt="image" src="https://github.com/adityakmrmishra/Geet/assets/114161683/9188587a-7b76-4f7f-ad8d-e886e5025a7b">

**Comment by adityakmrmishra** [comment]
@kartikp962 start working on it.

**Comment by Keshav-Aneja** [comment]
Can I work on this?

**Comment by adityakmrmishra** [comment]
> Can I work on this?

It's already assigned
