### ISSUE TITLE
Background color Modification in light mode

### ISSUE THREAD

**Issue by amrahs02** [adityakmrmishra/Geet#26]
**Is your feature request related to a problem? Please describe.**
Color is a very subjective thing but here I think the yellow color looks so odd, So I want to modify the color in light mode

**Describe the solution you'd like**
I want to change the color of whole page in Light mode

**Additional context**
it will look like this once It was changed
![Screenshot from 2023-10-03 19-22-13](https://github.com/adityakmrmishra/Geet/assets/65103353/f98d2468-c766-4f78-9cf8-0852b707c713)

**Comment by PUJAmangale1221** [comment]
Hello Maintainers,

I'm interested in contributing to this issue under hacktoberfest and would like to take it on. Could you please assign this issue to me, or let me know if there are any specific guidelines or additional information I should be aware of before I begin working on it?

Thank you!

**Comment by adityakmrmishra** [comment]
pls go through issue #14
