### ISSUE TITLE
Background color of search results

### ISSUE THREAD

**Issue by uday-kiran-001** [adityakmrmishra/Geet#30]
**Describe the bug**
Search results are not clearly visible because of it's background color

**Screenshots**
<img width="239" alt="Screenshot 2023-10-04 175710" src="https://github.com/adityakmrmishra/Geet/assets/116891059/2b21c29a-8670-4d7c-b669-7a3fade8ef4f">

**Comment by SurajPrakash24** [comment]
Can You please assign it to me. I would like to contribute

**Comment by uday-kiran-001** [comment]
@adityakmrmishra Could I know why is this issue closed?

**Comment by adityakmrmishra** [comment]
Don't worry there was a little confusion I'm reopening it

**Comment by uday-kiran-001** [comment]
@adityakmrmishra I have made changes which solves this issue and pulled a request #34
