### ISSUE TITLE
Copyright logo can be added in the footer

### ISSUE THREAD

**Issue by okaydivyansh** [adityakmrmishra/Geet#36]
**Is your feature request related to a problem? Please describe.**
It is a great idea to always showcase your work with authentication so that no one else can use the screenshots of the webpage as there is no copyright logo with "aditya mishra" or even name of the git repo 2023

**Describe the solution you'd like**
I want to add a copyright logo

**Describe alternatives you've considered**
I can even add github logo which would redirect to github repo on being clicked

**Additional context**
![image](https://github.com/adityakmrmishra/Geet/assets/94864199/a6beadb5-930e-4f69-96d7-2fcb61e6b7d7)
Just right there in the yellow space at the end, i would like to add the respective logos

**Comment by pragyamishra56** [comment]
@okaydivyansh Could you this assign this issue with me if would be possible
