### ISSUE TITLE
[ Enhancement] UI/UX: Improve Colors, Fonts, and Aesthetics

### ISSUE THREAD

**Issue by ayushichoudhary-19** [adityakmrmishra/Geet#5]
**Issue Description:**
The current UI/UX of the webpage requires enhancements to achieve a more aesthetically pleasing design. Here are the specific issues that need attention:

**1. Background Color:**
   - **Problem:** The yellow/mustard color used as the main background in light mode can be visually unattractive.
   - **Solution:** Consider using a more visually appealing background color to enhance the overall aesthetics.

**2. Font Choice:**
   - **Problem:** The current font choice may not provide an aesthetically pleasing look.
   - **Solution:** Opt for a more visually appealing font to improve the overall aesthetics.

**3. Search Bar Padding/Color:**
   - **Problem:** The search bar at the top lacks proper padding and also the gray color isn't very appealing.
   - **Solution:** Adjust the padding and color of the search bar to achieve a more visually pleasing and balanced appearance.

**Screenshot**
![image](https://github.com/adityakmrmishra/Geet/assets/73214455/791591e8-78d6-4246-9427-2b78b2d52dbb)

I have experience in UI/UX design and **would like to contribute** to improving the visual appeal.

**Comment by l-ashish-gupta-l** [comment]
Thank you for bringing these UI/UX concerns to our attention. We appreciate your willingness to contribute to improving the visual appeal of our repository. Before we can move forward, we'd like to see your proposed enhancements in a Figma design. This will help us assess the changes and ensure they align with our project's goals and user experience.

Please provide us with a Figma link to your design improvements when you're ready. Once we review and verify the changes, we can discuss the possibility of assigning you the project or collaborating on implementing the enhancements.

Looking forward to seeing your design ideas!

**Comment by ayushichoudhary-19** [comment]
Sure, will send the designs by tonight.

**Comment by ayushichoudhary-19** [comment]
### Please review the designs and provide your feedback:

#### Light/Dark Mode - Overall UI
![image](https://github.com/adityakmrmishra/Geet/assets/73214455/a19fa65f-1178-44e0-9ac7-a1c6611e6f61)

![image](https://github.com/adityakmrmishra/Geet/assets/73214455/2dc3c55b-fa76-4738-bdae-b69a6e9b6bf7)

#### SearchBars
![image](https://github.com/adityakmrmishra/Geet/assets/73214455/e72ca4bd-dac0-49b9-a484-104f5348a2dd)
![image](https://github.com/adityakmrmishra/Geet/assets/73214455/e9c7e34c-0b1c-4463-933d-783fbc251de0)

#### HoverEffects:
![image](https://github.com/adityakmrmishra/Geet/assets/73214455/af14523b-28f9-4c61-b6a8-f7f4abe35cef)
![image](https://github.com/adityakmrmishra/Geet/assets/73214455/ba2bf7f5-54b9-4a49-af0c-6d392630a713)

**Comment by adityakmrmishra** [comment]
Hi @ayushichoudhary-19 , 

Thank you for taking the time to contribute to our project and for sharing your design ideas. We appreciate your effort and willingness to help improve the UI/UX.

I've reviewed the design you shared, and I want to express my gratitude for your contribution. However, I believe there's room for exploring different design directions to ensure that our project's UI/UX stands out and aligns with our vision.

Our goal is to create a unique and visually appealing user experience that sets our project apart. To achieve this, I encourage you to consider trying some alternative design concepts. Don't hesitate to experiment and think outside the box to create something distinctive.

Feel free to share any new design iterations or ideas you come up with. We value your creativity, and your contributions are essential to making our project even better. If you have any questions or need further guidance, please don't hesitate to reach out.

Once again, thank you for your dedication to our project, and I look forward to seeing your innovative design concepts.

**Comment by Vivek7038** [comment]
should i make the changes based on the designs

**Comment by ayushichoudhary-19** [comment]
> Hi @ayushichoudhary-19 ,
> 
> Thank you for taking the time to contribute to our project and for sharing your design ideas. We appreciate your effort and willingness to help improve the UI/UX.
> 
> I've reviewed the design you shared, and I want to express my gratitude for your contribution. However, I believe there's room for exploring different design directions to ensure that our project's UI/UX stands out and aligns with our vision.
> 
> Our goal is to create a unique and visually appealing user experience that sets our project apart. To achieve this, I encourage you to consider trying some alternative design concepts. Don't hesitate to experiment and think outside the box to create something distinctive.
> 
> Feel free to share any new design iterations or ideas you come up with. We value your creativity, and your contributions are essential to making our project even better. If you have any questions or need further guidance, please don't hesitate to reach out.
> 
> Once again, thank you for your dedication to our project, and I look forward to seeing your innovative design concepts.

Thank you @adityakmrmishra for your feedback and for taking the time to review my designs.

Whenever I contribute, I make sure not to play around with the main essence/design of a project but rather focus on enhancing the existing elements. This may be why the design might not have seemed distinctive to you.

I absolutely understand the importance of creating a unique UI, but unfortunately, due to time constraints, I won't be able to explore alternative design concepts at this moment. However, I'm open to revisiting this in the future if time permits.

Once again, thank you for the feedback.

**Comment by parinitapatil** [comment]
I will send the design today as soon as possible.
