### ISSUE TITLE
 Improve Color Scheme and Font Style for Better Readability

### ISSUE THREAD

**Issue by MehakMantri** [adityakmrmishra/Geet#6]
Problem:

The current color scheme and font style used on the website could benefit from enhancements to create a more visually appealing and reader-friendly experience. The existing choices may not fully align with the desired aesthetics and can impact readability.

Description:
Color Scheme: The current color scheme may lack vibrancy and cohesiveness, which can affect the overall look and feel of the website. Improving the color palette can make the site more visually engaging and memorable.

Font Style: The choice of fonts plays a significant role in user experience. The current font style may not provide the best readability or may not align with the website's branding. Enhancing the font selection can improve readability and reinforce the website's identity.

Suggested Enhancements:
Color Scheme: 
> Considering color theory principles, I recommend incorporating more aesthetically pleasing colors into the website's design.
> Also, ensure that the selected colors provide adequate contrast for text and background elements.

Font Style:
> We should look for different fonts that are both aesthetically pleasing and easy to read.
> Also to ensure that the font choice aligns with the website's brand and content.

Screenshot:
![g1](https://github.com/adityakmrmishra/Geet/assets/114497437/d5468c92-509f-402a-9d8d-df0f6abf6b1e)

I'm looking forward to collaborating on this improvement.

**Comment by l-ashish-gupta-l** [comment]
Hi there,

Thanks for highlighting these UI/UX concerns and offering to help improve the design. To better understand your proposed changes, could you please share a Figma link with your design enhancements?
 Once we review and confirm the improvements, we can discuss the possibility of assigning you the project.

Looking forward to seeing your design ideas!

**Comment by parinitapatil** [comment]
is this issue included in hactoberfest? Can you assign me this.
