### ISSUE TITLE
BUG : RESIZE SEARCH BAR AND THE MODE CHNAGE BUTTON

### ISSUE THREAD

**Issue by dreeaamie** [adityakmrmishra/Geet#8]
**Describe the bug**
size of the search bar and the dark-light mode change button should be nearly symmetrical to look well favoured 

**To Reproduce**

**desktop pc**
 - Browser [chrome]
 - Version [Version 117.0.5938.92 ]

[ IMAGE ]
(https://github.com/adityakmrmishra/Geet/assets/121973953/3c67727f-79b5-49b0-96e6-3abf211d7cd2)

**Comment by adisuyash** [comment]
I think that there are ISSUEs, which addresses the same (#6 #5)
Check the issues first before raising any new issue
